Repository opendp/opendp, pull requests merged in 2025-04, with the labels that each got.

#2159 prove make_expr_datetime_component and match_datetime_component
  rust/src/transformations/make_stable_expr/namespace_dt/expr_datetime_component/make_expr_datetime_component.tex
  rust/src/transformations/make_stable_expr/namespace_dt/expr_datetime_component/match_datetime_component.tex
  rust/src/transformations/make_stable_expr/namespace_dt/expr_datetime_component/mod.rs
  rust/src/transformations/make_stable_expr/namespace_dt/expr_datetime_component/pseudocode/make_expr_datetime_component.py
  rust/src/transformations/make_stable_expr/namespace_dt/expr_datetime_component/pseudocode/match_datetime_component.py
  rust/src/transformations/make_stable_expr/namespace_dt/expr_datetime_component/test.rs
Labels: Proof

#1734 docs: quantiles theory section
  docs/source/theory/index.rst
  docs/source/theory/mechanisms/exponential-mechanism-quantiles.ipynb
  docs/source/theory/mechanisms/index.rst
Labels: docs, docs-polars

#2156 feat: prove make_expr_strptime
  rust/src/transformations/make_stable_expr/namespace_str/expr_strptime/make_expr_strptime.tex
  rust/src/transformations/make_stable_expr/namespace_str/expr_strptime/pseudocode/make_expr_strptime.py
Labels: Proof

#1126 feat: mechanism: add `make_canonical_noise`
  docs/source/api/user-guide/measurements/canonical-noise-mechanism.ipynb
  docs/source/api/user-guide/measurements/index.rst
  python/src/opendp/_lib.py
  python/src/opendp/context.py
  python/src/opendp/extras/examples/__init__.py
  python/src/opendp/extras/numpy/canonical.py
  python/test/extras/test_canonical_noise.py
  python/test/test_meas.py
  rust/src/lib.sty
  rust/src/measurements/canonical_noise/approximate_to_tradeoff.tex
  rust/src/measurements/canonical_noise/ffi.rs
  rust/src/measurements/canonical_noise/make_canonical_noise.tex
  rust/src/measurements/canonical_noise/mod.rs
  rust/src/measurements/canonical_noise/pseudocode/approximate_to_tradeoff.py
  rust/src/measurements/canonical_noise/pseudocode/make_canonical_noise.py
  rust/src/measurements/canonical_noise/ref.bib
  rust/src/measurements/canonical_noise/test.rs
  rust/src/measurements/mod.rs
  rust/src/traits/samplers/psrn/canonical/InverseCDF_for_CanonicalRV.tex
  rust/src/traits/samplers/psrn/canonical/mod.rs
  rust/src/traits/samplers/psrn/canonical/pseudocode/InverseCDF_for_CanonicalRV.py
  rust/src/traits/samplers/psrn/canonical/pseudocode/quantile_cnd.py
  rust/src/traits/samplers/psrn/canonical/quantile_cnd.tex
  rust/src/traits/samplers/psrn/canonical/ref.bib
  rust/src/traits/samplers/psrn/canonical/test.rs
  rust/src/traits/samplers/psrn/gumbel/mod.rs
  rust/src/traits/samplers/psrn/mod.rs
Labels: Proof, vetting
